# Generated by Django 4.2.1 on 2023-05-28 00:30

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=2000)),
                ('rating', models.IntegerField()),
                ('release_date', models.CharField(max_length=11)),
                ('popularity', models.IntegerField()),
                ('img', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('duration', models.IntegerField()),
                ('starting_date', models.DateField(default=django.utils.timezone.now)),
                ('ending_date', models.DateField(default=datetime.datetime(2023, 6, 4, 0, 30, 19, 611902, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
