# Generated by Django 4.2.1 on 2023-05-28 00:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='popularity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 0, 37, 53, 404514, tzinfo=datetime.timezone.utc)),
        ),
    ]
