# Generated by Django 4.2.1 on 2023-05-28 12:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_movie_popularity_alter_movie_rating_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 12, 43, 36, 565902, tzinfo=datetime.timezone.utc)),
        ),
    ]
