# Generated by Django 4.2.1 on 2023-05-28 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_rental_ending_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rental',
            name='title',
        ),
        migrations.AddField(
            model_name='rental',
            name='movie_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 18, 10, 25, 368240, tzinfo=datetime.timezone.utc)),
        ),
    ]
