# Generated by Django 4.2.1 on 2023-05-28 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_rental_title_rental_movie_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 19, 24, 49, 540530, tzinfo=datetime.timezone.utc)),
        ),
    ]
