# Generated by Django 4.2.1 on 2023-05-28 19:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_rental_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 4, 19, 36, 50, 843407, tzinfo=datetime.timezone.utc)),
        ),
    ]
