# Generated by Django 4.2.1 on 2023-05-29 00:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_rental_ending_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateField(default=datetime.datetime(2023, 6, 5, 0, 6, 34, 508000, tzinfo=datetime.timezone.utc)),
        ),
    ]
