# Generated by Django 4.2.1 on 2023-05-30 03:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_rental_ending_date_alter_rental_starting_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 6, 24, 22, 730551)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='starting_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 6, 24, 22, 730551)),
        ),
    ]
