# Generated by Django 4.2.1 on 2023-05-30 03:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_rental_ending_date_alter_rental_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='movie_title',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 6, 6, 36, 50, 392947)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='starting_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 30, 6, 36, 50, 392947)),
        ),
    ]
