# Generated by Django 4.2.1 on 2023-06-04 23:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_rental_ending_date_alter_rental_starting_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='rental',
            name='ending_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 12, 2, 26, 1, 693177)),
        ),
        migrations.AlterField(
            model_name='rental',
            name='starting_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 6, 5, 2, 26, 1, 693177)),
        ),
    ]
