export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const MOVIE_GET_REQUEST = "MOVIE_GET_REQUEST";
export const MOVIE_GET_SUCCESS = "MOVIE_GET_SUCCESS";
export const MOVIE_GET_FAIL = "MOVIE_GET_FAIL";

export const MOVIE_UPDATE_REQUEST = "MOVIE_UPDATE_REQUEST";
export const MOVIE_UPDATE_SUCCESS = "MOVIE_UPDATE_SUCCESS";
export const MOVIE_UPDATE_FAIL = "MOVIE_UPDATE_FAIL";

export const MOVIE_DELETE_REQUEST = "MOVIE_DELETE_REQUEST";
export const MOVIE_DELETE_SUCCESS = "MOVIE_DELETE_SUCCESS";
export const MOVIE_DELETE_FAIL = "MOVIE_DELETE_FAIL";

export const MOVIE_CREATE_REQUEST = "MOVIE_CREATE_REQUEST";
export const MOVIE_CREATE_SUCCESS = "MOVIE_CREATE_SUCCESS";
export const MOVIE_CREATE_FAIL = "MOVIE_CREATE_FAIL";
