export const MOVIE_LIST_REQUEST = "MOVIE_LIST_REQUEST";
export const MOVIE_LIST_SUCCESS = "MOVIE_LIST_SUCCESS";
export const MOVIE_LIST_FAIL = "MOVIE_LIST_FAIL";

export const MOVIE_GET_REQUEST = "MOVIE_GET_REQUEST";
export const MOVIE_GET_SUCCESS = "MOVIE_GET_SUCCESS";
export const MOVIE_GET_FAIL = "MOVIE_GET_FAIL";
