export const RENTAL_CREATE_REQUEST = "RENTAL_CREATE_REQUEST";
export const RENTAL_CREATE_SUCCESS = "RENTAL_CREATE_SUCCESS";
export const RENTAL_CREATE_FAIL = "RENTAL_CREATE_REQUEST";

export const RENTAL_LIST_REQUEST = "RENTAL_LIST_REQUEST";
export const RENTAL_LIST_SUCCESS = "RENTAL_LIST_SUCCESS";
export const RENTAL_LIST_FAIL = "RENTAL_LIST_FAIL";
export const RENTAL_LIST_RESET = "RENTAL_LIST_RESET";
